---
title: Base de donnée
---

classDiagram


    class Utilisateurs {
        #Identifiant
        Mdp(VARCHAR = 500 (HASH)
        LienPdp(VARCHAR = 500)
        Datecreation(DATE)
        isAdmin(bool)
    }

    class Jeux {
        #ID
        NomJeux(VARCHAR = 100)
        NbLikes(int)

    }

    class Classement {
        #Id
        id_user
        id_jeux
        pts(int)
        rang(int)
    }
    
    class Parties {
        #id
        joueurs(array)
    }

    class historique {

    }